config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :users
  resources :visits
  resources :visitors
  resources :sectors
  resources :units
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/visitor.rb
class Visitor < ApplicationRecord
    mount_uploader :photo, AvatarUploader
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /visitors or /visitors.json
  def index
    if params[:search].present?
      @visitors = Visitor.where(cpf: params[:search])
    else
      @visitors = Visitor.all
    end
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:description, :cpf, :rg, :phone, :photo)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor) do |form| %>
  <% if visitor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :rg, style: "display: block" %>
    <%= form.text_field :rg %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :foto, style: "display: block" %>
    <%= form.file_field :photo %>
  </div>

  <div>
    <br>
    <%= form.submit set_button_name, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/visitors/_visitor.html.erb
<div id="<%= dom_id visitor %>">
  <p>
    <strong>Nome:</strong>
    <%= visitor.description %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= visitor.cpf %>
  </p>

  <p>
    <strong>Rg:</strong>
    <%= visitor.rg %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= visitor.phone %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= image_tag(visitor.photo.to_s, size: "40x40", style: "border-radius: 30%") %>
  </p>

</div>

app/views/visitors/edit.html.erb
<h1>Editar visitante</h1>

<%= render "form", visitor: @visitor %>

<br>

<div>
  <%= link_to "Mostrar este visitante", @visitor, class: "btn btn-dark" %> 
  <%= link_to "Voltar", visitors_path, class: "btn btn-dark" %>
</div>

app/views/visitors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visitantes</h1>

<%= form_tag(visitors_path, method: :get) do %>
  <%= text_field_tag "search", nil, placeholder: "Pesquisa cpf" %>
  <%= submit_tag "Pesquisar", class: "btn btn-dark"%>
<% end %>
<br>
<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>CPF</th>
      <th>RG</th>
      <th>Telefone</th>
      <th>Foto</th>
      <th colspam></th>
      <th colspam></th>
      <th colspam></th>
    </tr>
  </thead>
  <tbody>
    <% @visitors.each do |visitor| %>
      <tr>
        <td><%= visitor.id %></td>
        <td><%= visitor.description %></td>
        <td><%= visitor.cpf %></td>
        <td><%= visitor.rg %></td>
        <td><%= visitor.phone %></td>
        <td><%= image_tag(visitor.photo.to_s, size: "40x40", style: "border-radius: 30%") %></td>
        <td><%= link_to "Mostrar", visitor, class: "btn btn-dark" %></td>
        <td><%= link_to "Editar", edit_visitor_path(visitor), class: "btn btn-dark" %></td>
        <td><%= link_to "Apagar", visitor, method: :delete, class: "btn btn-dark", data: { confirm: "Você tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Novo", new_visitor_path, class: "btn btn-dark" %>

app/views/visitors/new.html.erb
<h1>Novo visitante</h1>

<%= render "form", visitor: @visitor %>

<br>

<div>
  <%= link_to "Voltar", visitors_path, class: "btn btn-dark" %>
</div>

app/views/visitors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visitor %>

<div>
  <%= link_to "Editar", edit_visitor_path(@visitor), class: "btn btn-dark" %> 
  <%= link_to "Voltar", visitors_path, class: "btn btn-dark" %>

  <br><br>

  <%= button_to "Deletar este visitante", @visitor, class: "btn btn-dark", method: :delete %>
</div>