config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :users
  resources :visits
  resources :visitors
  resources :sectors
  resources :units
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :visitor
  belongs_to :unit
  belongs_to :sector
  enum status: [:espera, :realizada]
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /visits or /visits.json
  def index
    @visits = Visit.all

    if params[:id]
      @visit_status = Visit.find(params[:id])
      if @visit_status.espera?
        @visit_status.realizada!
        flash.now[:notice] = "Visita finalizada com sucesso!"
      end
    end
  end

  # GET /visits/1 or /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits or /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully created." }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully updated." }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1 or /visits/1.json
  def destroy
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url, notice: "Visit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  private

    def set_status
      @visita.status = get_status
    end

    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:visitor_id, :unit_id, :sector_id, :status, :visit_date, :visit_moment)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
    def date_to_br_format(date)
        date.strftime("%d/%m/%Y")
    end

    def hour_to_br_format(time)
        time.strftime("%H:%M:%S")
    end
end

app/views/visits/_form.html.erb
<%= form_with(model: visit) do |form| %>
  <% if visit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% visit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.funcionario? %>
    <div>
      <%= form.label :status, style: "display: block" %>
      <%= form.select :status, Visit.statuses.keys %>
    </div>
  <% else %>
    <div>
      <%= form.label :cpf_visitante, style: "display: block" %>
      <%= form.select("visitor_id", Visitor.all.pluck(:cpf, :id), { include_blank: "Selecione..." }) %>
    </div>

    <div>
      <%= form.label :unidade, style: "display: block" %>
      <%= form.select("unit_id", Unit.all.pluck(:description, :id)) %>
    </div>

    <div>
      <%= form.label :setor, style: "display: block" %>
      <%= form.select("sector_id", Sector.all.pluck(:description, :id)) %>
    </div>

    <div>
      <%= form.label :status, style: "display: block" %>
      <%= form.select :status, Visit.statuses.keys %>
    </div>

    <div>
      <%= form.label :data_da_visita, style: "display: block" %>
      <%= form.date_field :visit_date %>
    </div>

    <div>
      <%= form.label :hora_da_visita, style: "display: block" %>
      <%= form.time_field :visit_moment %>
    </div>
  <% end %>
  <br>
  <div>
    <%= form.submit set_button_name, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/visits/_visit.html.erb
<div id="<%= dom_id visit %>">
  <p>
    <strong>Visitante:</strong>
    <%= visit.visitor.description %>
  </p>
  <p>
    <strong>Unidade:</strong>
    <%= visit.unit.description %>
  </p>
  <p>
    <strong>Setor:</strong>
    <%= visit.sector.description %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= visit.status.capitalize %>
  </p>
  <p>
    <strong>Data da Visita:</strong>
    <%= date_to_br_format(visit.visit_date) %>
  </p>
  <p>
    <strong>Hora da Visita:</strong>
    <%= hour_to_br_format(visit.visit_moment) %>
  </p>
</div>

app/views/visits/edit.html.erb
<h1>Editar visita</h1>

<%= render "form", visit: @visit, visita: @visita %>

<br>

<div>
  <%= link_to "Mostrar esta visita", @visit, class: "btn btn-dark" %> 
  <%= link_to "Voltar", visits_path, class: "btn btn-dark" %>
</div>

app/views/visits/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Visitas</h1>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>Visitante</th>
      <th>CPF</th>
      <th>RG</th>
      <th>Unidade</th>
      <th>Setor</th>
      <th>Status</th>
      <th>Data</th>
      <th>Hora</th>
      <th colspam="3"></th>
      <th colspam="3"></th>
      <th colspam="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.visitor.description %></td>
        <td><%= visit.visitor.cpf %></td>
        <td><%= visit.visitor.rg %></td>
        <td><%= visit.unit.description %></td>
        <td><%= visit.sector.description %></td>
        <td><%= visit.status.capitalize %></td>
        <td><%= date_to_br_format(visit.visit_date) %></td>
        <td><%= hour_to_br_format(visit.visit_moment) %></td>

        <% if can? :manage, Visit %>
          <td><%= link_to "Mostrar", visit, class: "btn btn-dark" %></td>
          <td><%= link_to "Editar", edit_visit_path(visit), class: "btn btn-dark" %></td>
          <td><%= link_to "Apagar", visit, class: "btn btn-dark", method: :delete, data: { confirm: "Você tem certeza?" } %></td>
        <% else %>
          <td><%= link_to "Mostrar", visit, class: "btn btn-dark" %></td>
          <% if visit.status == "espera" %>
            <td><%= link_to "Realizar", visits_path(id: visit), class: "btn btn-dark" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Visit %>
  <%= link_to "Novo", new_visit_path, class: "btn btn-dark" %>
<% end %>

app/views/visits/new.html.erb
<h1>Nova visita</h1>

<%= render "form", visit: @visit %>

<br>

<div>
  <%= link_to "Voltar", visits_path, class: "btn btn-dark" %>
</div>

app/views/visits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visit %>

<div>
  <%= link_to "Editar", edit_visit_path(@visit), class: "btn btn-dark" %> 
  <%= link_to "Voltar", visits_path, class: "btn btn-dark" %>

  <br><br>

  <% if can? :destroy, Visit %>
    <%= button_to "Deletar esta visita", @visit, class: "btn btn-dark", method: :delete %>
  <% end %>
</div>