config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :users
  resources :visits
  resources :visitors
  resources :sectors
  resources :units
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Controle de Entrada", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Início", root_path, class: "nav-link active", style: "aria-current=page" %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Usuários", users_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Unidades", units_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Setores", sectors_path, class: "nav-link" %>
            </li>
            <li class="nav-item nav-link">
              <strong>Usuário: </strong><%= current_user.description %>
            </li>
          <% elsif current_user.atendente %>
            <li class="nav-item">
              <%= link_to "Visitantes", visitors_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Visitas", visits_path, class: "nav-link" %>
            </li>
            <li class="nav-item nav-link">
              <strong>Usuário: </strong><%= current_user.description %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Visitas", visits_path, class: "nav-link" %>
            </li>
            <li class="nav-item nav-link">
              <strong>Usuário: </strong><%= current_user.description %>
            </li>
          <% end %>
          <li>
            <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-dark" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home</h1>

<% unless user_signed_in? %>
    <%= link_to "Login", new_user_session_path, class: "btn btn-dark" %>
<% end %>