config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :users
  resources :visits
  resources :visitors
  resources :sectors
  resources :units
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/unit.rb
class Unit < ApplicationRecord
    has_many :sectors
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource
  
  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:description)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <br>
  
  <div>
    <%= form.submit set_button_name, class: "btn btn-dark" %>
  </div>
<% end %>

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Nome:</strong>
    <%= unit.description %>
  </p>

</div>

app/views/units/edit.html.erb
<h1>Editar unidade</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Mostrar esta unidade", @unit, class: "btn btn-dark" %>
  <%= link_to "Voltar", units_path, class: "btn btn-dark" %>
</div>

app/views/units/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Unidades</h1>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>Nome</th>
      <th colspam></th>
      <th colspam></th>
      <th colspam></th>
    </tr>
  </thead>
  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.description %></td>
        <td><%= link_to "Mostrar", unit, class: "btn btn-dark" %></td>
        <td><%= link_to "Editar", edit_unit_path(unit), class: "btn btn-dark" %></td>
        <td><%= link_to "Apagar", unit, class: "btn btn-dark", method: :delete, data: { confirm: "Você tem certeza?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Novo", new_unit_path, class: "btn btn-dark" %>

app/views/units/new.html.erb
<h1>Nova unidade</h1>

<%= render "form", unit: @unit %>

<br>

<div>
  <%= link_to "Voltar", units_path, class: "btn btn-dark" %>
</div>

app/views/units/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @unit %>

<div>
  <%= link_to "Editar", edit_unit_path(@unit), class: "btn btn-dark" %>
  <%= link_to "Voltar", units_path, class: "btn btn-dark" %>

  <br><br>
  
  <%= button_to "Apagar esta unidade", @unit, class: "btn btn-dark", method: :delete %>
</div>